# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Api-gateway-nikokiru

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7088f00084294fe89827196215ed4d68 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_747ff1faa9f142419058d93a4e16a7be }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7088f00084294fe89827196215ed4d68 }}/api-gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Api-gateway-nikokiru'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c63783ad713044759458d8ae4fd33ded }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7088f00084294fe89827196215ed4d68 }}/api-gateway:${{ github.sha }}'